@host = http://localhost:3001


###
GET {{host}}/api/users?pageNumber=5

###
GET {{host}}/api/users
x-auth: 23423

###
GET {{host}}/users?name=w&email=H

###
    GET {{host}}/users?pageNumber=3

###

POST {{host}}/users
Content-Type: application/json

{
    "name":"Marta",
    "email": "marta@test.com"
}


###

GET {{host}}/users

###

POST {{host}}/users
Content-Type: application/json

{
    "name":"asdf"
}

###

PUT {{host}}/users/2
Content-Type: application/json

{
    "name":"user2",
    "email":"user2@test.com"
}

###
DELETE {{host}}/users/4
x-auth: 345346